apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilist-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=hub.docker.com/repository/docker/ravennaras/cilist-staging
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest           
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds            
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/rvnaras/cilsy-list.git
    targetRevision: HEAD
    path: stagingmanifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
