apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilist-production-be
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ravennaras/cilist-production-be  
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest        
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds            
    argocd-image-updater.argoproj.io/git-branch: main 
spec:
  project: default
  source:
    repoURL: https://github.com/rvnaras/cilsy-list.git
    targetRevision: HEAD
    path: productionbe
  destination: 
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilist-production-fe
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ravennaras/cilist-production-fe   
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest        
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds            
    argocd-image-updater.argoproj.io/git-branch: main 
spec:
  project: default
  source:
    repoURL: https://github.com/rvnaras/cilsy-list.git
    targetRevision: HEAD
    path: productionfe
  destination: 
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

