apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fe
data:
    REACT_APP_BACKEND_URL: "bp.musyaffadli.com/be" 
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Rollout
    name: cilist-fe
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: ClusterIP
 ---
 apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc-preview
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cilist-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist
      tier: frontend
  template:
    metadata:
      labels:
        app: cilist
        tier: frontend
    spec:
      containers:
      - image: ravennaras/cilist:fejenkins
        imagePullPolicy: Always
        name: cilist-fe
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-fe
              key: REACT_APP_BACKEND_URL
      restartPolicy: Always
 strategy:
   blueGreen:
     autoPromotionEnabled: false
     activeService: cilist-fe-svc
     previewService: cilist-fe-svc-preview
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cilist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: nginx
  rules:
    - host: bp.musyaffadli.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cilist-fe-svc
              port:
                number: 3000
        - path: /be
          pathType: Prefix
          backend:
            service:
              name: cilist-be-svc
              port:
                number: 5000
         - path: /fe-prv
          pathType: Prefix
          backend:
            service:
              name: cilist-fe-svc-preview
              port:
                number: 3001
         - path: /be-prv
          pathType: Prefix
          backend:
            service:
              name: cilist-be-svc-preview
              port:
                number: 5001
