apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fe
data:
    REACT_APP_BACKEND_URL: "http://dbc.musyaffadli.com" 
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cilist-fe
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc-preview
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: cilist-fe-svc-preview
# spec:
#   type: NodePort
#   selector:
#     app: cilist-fe
#   ports:
#     - port: 80
#       targetPort: http
#       protocol: TCP
#       name: http
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cilist-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist
      tier: frontend
  template:
    metadata:
      labels:
        app: cilist
        tier: frontend
    spec:
      containers:
      - image: ravennaras/cilist-production-fe:fe-6141
        imagePullPolicy: Always
        name: cilist-fe
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-fe
              key: REACT_APP_BACKEND_URL
      restartPolicy: Always
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: cilist-fe-svc
      previewService: cilist-fe-svc-preview
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cilist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/proxy-body-size: 100M
    # kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/app-root: /
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: nginx
  rules:
    - host: bp.musyaffadli.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cilist-fe-svc
              port:
                number: 3000
        - path: /preview
          pathType: Prefix
          backend:
            service:
              name: cilist-fe-svc-preview
              port:
                number: 3000
