apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fe
data:
    REACT_APP_BACKEND_URL: "http://ec2-54-226-249-115.compute-1.amazonaws.com:30100"
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-fe-svc
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cilist
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cilist
      tier: frontend
  template:
    metadata:
      labels:
        app: cilist
        tier: frontend
    spec:
      containers:
      - image: ravennaras/cilist-staging-fe:fe-130d9
        name: cilist-fe
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-fe
              key: REACT_APP_BACKEND_URL
      restartPolicy: Always
