apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.backend.service }}
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: {{ .Values.deployment.backend.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.backend.targetport }}
  selector:
    app: {{ .Values.labels.name }}
    tier: {{ .Values.labels.backend.tier }}
  type: ClusterIP
