apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.Y2lsaXN0LXNlY3JldA }}
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cGFzc3dvcmQ=
  DB_SELECT: cGVvcGxl
  DB_ENDPOINT: ZGIubXVzeWFmZmFkbGkuY29t
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
