apiVersion: v1
kind: Secret
metadata:
  name: cilist-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cGFzc3dvcmQ=
  DB_SELECT: cGVvcGxl
  DB_ENDPOINT: ZGIubXVzeWFmZmFkbGkuY29t
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-be
data:
  BASE_URL_PORT: "5000"
  DATABASE_PORT: "3306"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: be-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cilist-be
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-be-svc
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cilist
    tier: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cilist-be-svc-preview
spec:
  ipFamilies:
  - IPv4
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: cilist
    tier: backend
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cilist-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist
      tier: backend
  template:
    metadata:
      labels:
        app: cilist
        tier: backend
    spec:
      containers:
      - image: ravennaras/cilist-production-be:bejenkins
        imagePullPolicy: Always
        name: cilist-be
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: BASE_URL_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-be
              key: BASE_URL_PORT
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-be
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_PASS
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_ENDPOINT
        - name: DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              name: cilist-secret
              key: DB_SELECT
      restartPolicy: Always
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: cilist-be-svc
      previewService: cilist-be-svc-preview
